title: Open Mainframe Project TAC
description: Materials and processes for the Open Mainframe Project TAC
logo: "https://artwork.openmainframeproject.org/other/open-mainframe-project/horizontal/color/open-mainframe-project-horizontal-color.svg"
theme: just-the-docs

exclude: [
  "README.md",
  "completed.md",
  "dco-signoffs/",
  "Gemfile", 
  "Gemfile.lock", 
  "package.json", 
  "package-lock.json",
  "CODE_OF_CONDUCT.md",
  "LICENSE",
  "vendor"
]

back_to_top: true
back_to_top_text: "Back to top"

gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/openmainframeproject/tac" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
gh_edit_view_mode: "tree"

landscape_url: 'https://landscape.openmainframeproject.org'
calendar_url: 'https://calendar.openmainframeproject.org'
slack_url: 'https://slack.openmainframeproject.org'
directed_fund_charter_url: 'https://charter.openmainframeproject.org'
tac_issues_url: 'https://github.com/openmainframeproject/tac/issues/new'
helpdesk_url: "https://servicedesk.openmainframeproject.org"
tac_mailing_list_url: "https://lists.openmainframeproject.org/g/omp-technical"
website_url: "https://openmainframeproject.org"
blog_url: "https://openmainframeproject.org/blog"

# Founation Settings
membership_top_tier: 'Platinum'
foundation_name: "Open Mainframe Project"
clotributor_name: openmainframeproject

aux_links:
  "Need help or have a question? Contact us here":
    - "//servicedesk.openmainframeproject.org"
footer_content: Copyright &copy; The Linux Foundation&reg;. All rights reserved. The Linux Foundation has registered trademarks and uses trademarks. For a list of trademarks of The Linux Foundation, please see our <a href="https://www.linuxfoundation.org/trademark-usage">Trademark Usage</a> page. Linux is a registered trademark of Linus Torvalds. <a href="http://www.linuxfoundation.org/privacy">Privacy Policy</a> and <a href="http://www.linuxfoundation.org/terms">Terms of Use</a>.

readme_index:
  with_frontmatter: true
  
ga_tracking: 359859504
ga_tracking_anonymize_ip: true

kramdown:
  input: GFM
  extensions:
    - autolink
