title: Open Mainframe Project TAC
description: Materials and processes for the Open Mainframe Project TAC
logo: "https://artwork.openmainframeproject.org/other/open-mainframe-project/horizontal/color/open-mainframe-project-horizontal-color.svg"
theme: just-the-docs
repository: openmainframeproject/tac

exclude: [
  "README.md",
  "completed.md",
  "dco-signoffs/",
  "Gemfile", 
  "Gemfile.lock", 
  "package.json", 
  "package-lock.json",
  "CODE_OF_CONDUCT.md",
  "LICENSE",
  "vendor"
]

back_to_top: true
back_to_top_text: "Back to top"

gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/openmainframeproject/tac" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
gh_edit_view_mode: "tree"

# Various URLs used across the site
landscape_url: 'https://landscape.openmainframeproject.org'
calendar_url: 'https://calendar.openmainframeproject.org'
slack_url: 'https://slack.openmainframeproject.org'
directed_fund_charter_url: 'https://charter.openmainframeproject.org'
tac_issues_url: 'https://github.com/openmainframeproject/tac/issues/new?template=01-tac-agenda.yml'
helpdesk_url: "https://servicedesk.openmainframeproject.org"
mailing_list_url: "https://lists.openmainframeproject.org"
wiki_url: "https://wiki.openmainframeproject.org"
lfx_insights_url: "https://insights.lfx.linuxfoundation.org/foundation/open-mainframe-project"
tac_mailing_list_url: "https://lists.openmainframeproject.org/g/omp-technical"
tac_mailing_list_email: omp-technical@lists.openmainframeproject.org
tac_private_mailing_list_email: omp-tac-private@lists.openmainframeproject.org
leads_mailing_list_email: omp-technical-leads@lists.openmainframeproject.org
website_url: "https://openmainframeproject.org"
blog_url: "https://openmainframeproject.org/blog"
tac_lfx_meeting_url: https://zoom-lfx.platform.linuxfoundation.org/meetings/open-mainframe-project?view=list&projects=open-mainframe-project
lfscanning_repo_url: https://github.com/lfscanning/spdx-omp
tac_member_list_url: https://openmainframeproject.org/about/technical-advisory-council
lf_staff_list_url: https://openmainframeproject.org/about/leadership
mission_statement_url: https://openmainframeproject.org/about/ 
tac_agenda_url: https://github.com/orgs/openmainframeproject/projects/21
artwork_url: 'https://artwork.openmainframeproject.org'
election_guidelines_url: 'https://github.com/openmainframeproject/foundation/blob/main/elections.md'

# Foundation Settings
foundation_name: "Open Mainframe Project"
clotributor_name: openmainframeproject
membership_top_tier: 'Platinum'
vote_of_tac_committee_title: "Industry Representatives"
vote_of_tac_committee_count: 2
archived_lifecycle_stage: "Emeritus"
tac_projects: 
  - "Active Stage Projects"
project_types:
  - singular: "Project"
    plural: "Projects"
  - singular: "Working Group"
    plural: "Working Groups"

aux_links:
  "Need help or have a question? Contact us here":
    - "//servicedesk.openmainframeproject.org"
footer_content: Copyright &copy; The Linux Foundation&reg;. All rights reserved. The Linux Foundation has registered trademarks and uses trademarks. For a list of trademarks of The Linux Foundation, please see our <a href="https://www.linuxfoundation.org/trademark-usage">Trademark Usage</a> page. Linux is a registered trademark of Linus Torvalds. <a href="http://www.linuxfoundation.org/privacy">Privacy Policy</a> and <a href="http://www.linuxfoundation.org/terms">Terms of Use</a>.

readme_index:
  with_frontmatter: true
  
ga_tracking: 359859504
ga_tracking_anonymize_ip: true

kramdown:
  input: GFM
  extensions:
    - autolink
  parse_block_html: true
  toc_levels: 2..6

plugins:
  - jekyll-redirect-from

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "10.9.0"

callouts:
  note:
    title: Note
    color: blue

defaults:
  -
    scope: 
      path: "meetings/*/README.md"
      type: "pages"
    values:
      title: My Title
      parent: Meetings
